<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="style/styleHome.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
</head>
<body>
<section class="header">
    <#include 'top_nav.ftlh'>
    <div class="text-box">
        <h1>WELCOME TO ASTRLOGO</h1>
        <p>Know yourself together with us. The star map will help you build the right one and change your destiny.</p>
        <a href="/signIn" class="hero-btn">LOGIN</a>
    </div>

</section>

<section class="astroservices">
    <h1>Available astroservices</h1>
    <p>The most essential astroservices to answer your questions.</p>

    <div class="row">
        <div class="astroservices-col">
            <h3>Zodiac compatibility</h3>
            <p>Find out if you and your love interest or partner are soul mates, best friends, or a recipe for disaster.
                But no fear - even opposites can attract. Find out how you fare now. </p>
        </div>
        <div class="astroservices-col">
            <h3>Mercury retrograde calendar</h3>
            <p>Three times a year, the planet Mercury appears to travel backward across the sky. We refer to these
                periods as times when Mercury is in apparent retrograde motion, or simply ”Mercury retrograde.”</p>
        </div>
        <div class="astroservices-col">
            <h3>Zodiac signs</h3>
            <p>Learn more about your zodiac sign to shed light on your personality, love life, career, and more. Insight
                into your strengths, weaknesses, and life path are all accessible once you unpack your zodiac sign’s
                lessons during this life.</p>
        </div>
    </div>

</section>
</body>
</html>
